import React,{useEffect,useState}from'react'
import{Alert,AppBar,Box,Button,CircularProgress,Container,Divider,Drawer,IconButton,List,ListItemButton,ListItemText,Menu,MenuItem,Stack,TextField,Toolbar,Typography,useMediaQuery,useTheme}from'@mui/material'
import MenuIcon from'@mui/icons-material/Menu'
import KeyboardArrowDownIcon from'@mui/icons-material/KeyboardArrowDown'
import{ supabase }from'./supabase.js'
import ClientsModule from'./ClientsModule.jsx'
import ProductsScreen from'./ProductsScreen.jsx'
import ServicesScreen from'./ServicesScreen.jsx'
import ProceduresScreen from'./ProceduresScreen.jsx'
import PaymentsScreen from'./PaymentsScreen.jsx'
import CreditsScreen from'./CreditsScreen.jsx'
import RefundsScreen from'./RefundsScreen.jsx'
import FinanceScreen from'./FinanceScreen.jsx'
import ReconciliationScreen from'./ReconciliationScreen.jsx'
import InventoryScreen from'./InventoryScreen.jsx'
function LoginScreen({onSession}){const[email,setEmail]=useState('drrodolfocabezas@gmail.com'),[password,setPassword]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('');const submit=async e=>{e.preventDefault();setLoading(true);setError('');const{data,error:x}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(x){setError('No pudimos iniciar sesión. Revisá el correo y la contraseña.');setLoading(false);return}onSession(data.session);setLoading(false)};return <Box minHeight="100vh" display="grid" sx={{placeItems:'center',p:2}}><Box component="form" onSubmit={submit} sx={{width:'100%',maxWidth:430,bgcolor:'background.paper',p:{xs:3,sm:4},borderRadius:3,boxShadow:'0 20px 60px rgba(20,20,60,.10)'}}><Stack spacing={3}><Box><Typography variant="overline" color="text.secondary">Gestión clínica</Typography><Typography variant="h4" fontWeight={800}>Dr. Rodolfo Cabezas</Typography></Box>{error&&<Alert severity="error">{error}</Alert>}<TextField label="Correo" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><TextField label="Contraseña" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><Button type="submit" variant="contained" disabled={loading}>{loading?'Ingresando…':'Iniciar sesión'}</Button></Stack></Box></Box>}
const groups=[{label:'Pacientes',items:[['clients','Clientes'],['procedures','Procedimientos']]},{label:'Operación',items:[['services','Servicios'],['products','Productos'],['inventory','Inventario']]},{label:'Finanzas',admin:true,items:[['payments','Pagos'],['credits','Créditos'],['refunds','Resolver pagos'],['finance','Finanzas'],['reconciliation','Conciliación']]}]
function Navigation({section,setSection,role}){const theme=useTheme(),mobile=useMediaQuery(theme.breakpoints.down('md'));const[drawer,setDrawer]=useState(false),[anchor,setAnchor]=useState(null),[activeGroup,setActiveGroup]=useState(null);const allowed=groups.filter(g=>!g.admin||role==='admin');const choose=v=>{setSection(v);setDrawer(false);setAnchor(null)};if(mobile)return <><IconButton onClick={()=>setDrawer(true)} aria-label="Abrir navegación"><MenuIcon/></IconButton><Drawer anchor="right" open={drawer} onClose={()=>setDrawer(false)}><Box sx={{width:280,p:2}}><Typography fontWeight={800} mb={1}>Secciones</Typography>{allowed.map((g,i)=><Box key={g.label}>{i>0&&<Divider sx={{my:1}}/>}<Typography variant="overline" color="text.secondary" px={2}>{g.label}</Typography><List dense>{g.items.map(([v,l])=><ListItemButton key={v} selected={section===v} onClick={()=>choose(v)}><ListItemText primary={l}/></ListItemButton>)}</List></Box>)}</Box></Drawer></>;return <Stack direction="row" spacing={.5}>{allowed.map(g=><Box key={g.label}><Button color="inherit" endIcon={<KeyboardArrowDownIcon/>} onClick={e=>{setAnchor(e.currentTarget);setActiveGroup(g.label)}}>{g.label}</Button><Menu anchorEl={anchor} open={Boolean(anchor)&&activeGroup===g.label} onClose={()=>setAnchor(null)}>{g.items.map(([v,l])=><MenuItem key={v} selected={section===v} onClick={()=>choose(v)}>{l}</MenuItem>)}</Menu></Box>)}</Stack>}
export default function ClinicApp(){const[session,setSession]=useState(undefined),[organization,setOrganization]=useState(null),[role,setRole]=useState(''),[section,setSection]=useState('clients'),[loading,setLoading]=useState(false),[error,setError]=useState('');useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[]);useEffect(()=>{if(!session?.user?.id){setOrganization(null);setRole('');return}const go=async()=>{setLoading(true);const{data,error:e}=await supabase.from('organization_members').select('role,organization_id,organizations(id,name,slug,default_fx_crc_per_usd,settings)').eq('user_id',session.user.id).eq('active',true).limit(1);if(e||!data?.length)setError('Tu usuario no está asociado a una organización activa.');else{setRole(data[0].role);setOrganization(data[0].organizations)}setLoading(false)};go()},[session?.user?.id]);if(session===undefined||loading)return <Box minHeight="100vh" display="grid" sx={{placeItems:'center'}}><CircularProgress/></Box>;if(!session)return <LoginScreen onSession={setSession}/>;if(!organization)return <Container sx={{py:5}}>{error&&<Alert severity="error">{error}</Alert>}</Container>;const props={organization,userId:session.user.id,role};return <Box minHeight="100vh"><AppBar position="sticky" color="inherit" elevation={0} sx={{borderBottom:'1px solid',borderColor:'divider'}}><Toolbar sx={{gap:1}}><Box flex={1}><Typography fontWeight={800}>{organization.name}</Typography><Typography variant="caption">{role==='admin'?'Administrador':'Asistente'}</Typography></Box><Navigation section={section} setSection={setSection} role={role}/><Button color="inherit" onClick={async()=>{await supabase.auth.signOut();setSession(null)}}>Salir</Button></Toolbar></AppBar><Container maxWidth="lg" sx={{py:{xs:3,sm:5}}}>{section==='clients'&&<ClientsModule {...props}/>} {section==='products'&&<ProductsScreen {...props}/>} {section==='services'&&<ServicesScreen {...props}/>} {section==='procedures'&&<ProceduresScreen {...props}/>} {section==='payments'&&<PaymentsScreen {...props}/>} {section==='credits'&&<CreditsScreen {...props}/>} {section==='refunds'&&role==='admin'&&<RefundsScreen organization={organization} userId={session.user.id}/>} {section==='finance'&&role==='admin'&&<FinanceScreen {...props} onOrganizationUpdated={setOrganization}/>} {section==='reconciliation'&&role==='admin'&&<ReconciliationScreen {...props}/>} {section==='inventory'&&<InventoryScreen {...props}/>}</Container></Box>}
