import React,{useEffect,useMemo,useState}from'react'
import{Alert,Box,Button,Card,CardContent,Chip,Stack,Typography}from'@mui/material'
import AssignmentLateIcon from'@mui/icons-material/AssignmentLate'
import Inventory2Icon from'@mui/icons-material/Inventory2'
import WhatsAppIcon from'@mui/icons-material/WhatsApp'
import ReceiptLongIcon from'@mui/icons-material/ReceiptLong'
import AccountBalanceWalletIcon from'@mui/icons-material/AccountBalanceWallet'
import CheckCircleOutlineIcon from'@mui/icons-material/CheckCircleOutline'
import{ supabase }from'./supabase.js'
const startOfDay=d=>new Date(d.getFullYear(),d.getMonth(),d.getDate()),fmt=d=>new Date(`${d}T12:00:00`).toLocaleDateString('es-CR')
export default function DashboardScreen({organization,userId,role,onNavigate}){const[tasks,setTasks]=useState([]),[assignees,setAssignees]=useState([]),[products,setProducts]=useState([]),[containers,setContainers]=useState([]),[lastRec,setLastRec]=useState(null),[error,setError]=useState('');useEffect(()=>{const load=async()=>{const q=[supabase.from('tasks').select('*').eq('organization_id',organization.id).eq('status','pending'),supabase.from('task_assignees').select('*').eq('organization_id',organization.id),supabase.from('products').select('*').eq('organization_id',organization.id).eq('active',true),supabase.from('inventory_containers').select('id,product_id,status').eq('organization_id',organization.id)];if(role==='admin')q.push(supabase.from('reconciliation_batches').select('*').eq('organization_id',organization.id).eq('status','closed').order('week_end',{ascending:false}).limit(1).maybeSingle());const r=await Promise.all(q);if(r.some(x=>x.error)){setError('No se pudo cargar todo el resumen del día.');return}setTasks(r[0].data||[]);setAssignees(r[1].data||[]);setProducts(r[2].data||[]);setContainers(r[3].data||[]);if(role==='admin')setLastRec(r[4].data||null)};load()},[organization.id,userId,role]);const mine=useMemo(()=>{const ids=new Set(assignees.filter(a=>a.user_id===userId).map(a=>a.task_id));return tasks.filter(t=>ids.has(t.id)||t.assigned_to===userId)},[tasks,assignees,userId]);const today=startOfDay(new Date()),tomorrow=new Date(today);tomorrow.setDate(today.getDate()+1);const urgent=mine.filter(t=>t.due_at&&new Date(t.due_at)<tomorrow),overdue=mine.filter(t=>t.due_at&&new Date(t.due_at)<today),followups=mine.filter(t=>['procedure_followup','procedure_remarketing'].includes(t.reference_type)),collections=mine.filter(t=>t.reference_type==='procedure_collection');const lowStock=products.filter(p=>{const n=containers.filter(c=>c.product_id===p.id&&['open','closed'].includes(c.status)).length;return n<=Number(p.low_stock_threshold||0)});let recStatus=null;if(role==='admin'){if(lastRec){const end=new Date(`${lastRec.week_end}T12:00:00`),days=Math.floor((today-startOfDay(end))/86400000);recStatus={days,nextStart:new Date(end.getTime()+86400000),nextEnd:new Date(end.getTime()+7*86400000)}}else recStatus={days:999,nextStart:null,nextEnd:null}}
const metric=(icon,title,value,caption,section)=><Card variant="outlined" sx={{height:'100%',cursor:'pointer','&:hover':{bgcolor:'action.hover'}}} onClick={()=>onNavigate(section)}><CardContent><Stack spacing={1}><Box>{icon}</Box><Typography variant="h4" fontWeight={900}>{value}</Typography><Typography fontWeight={800}>{title}</Typography><Typography variant="body2" color="text.secondary">{caption}</Typography></Stack></CardContent></Card>;
return <Stack spacing={3}>{error&&<Alert severity="warning">{error}</Alert>}<Box><Typography variant="overline" color="text.secondary">Inicio</Typography><Typography variant="h4" fontWeight={900}>¿Qué necesita atención hoy?</Typography><Typography color="text.secondary">Tu espacio de entrada: pendientes, alertas y accesos rápidos.</Typography></Box>{role==='admin'&&recStatus&&<Alert severity={recStatus.days>=7?'error':recStatus.days>=6?'warning':'info'} action={<Button color="inherit" size="small" onClick={()=>onNavigate('reconciliation')}>Ir a conciliación</Button>}>{!lastRec?'No hay una conciliación cerrada todavía.':recStatus.days>=7?`Conciliación pendiente. El último período cerró el ${fmt(lastRec.week_end)}.`:recStatus.days>=6?`Mañana corresponde revisar la próxima conciliación. Último período: ${fmt(lastRec.week_start)} – ${fmt(lastRec.week_end)}.`:`Última conciliación cerrada: ${fmt(lastRec.week_start)} – ${fmt(lastRec.week_end)}.`}</Alert>}<Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'1fr 1fr',lg:'repeat(4,1fr)'},gap:2}}>{metric(<AssignmentLateIcon color={overdue.length?'error':'action'}/>, 'Urgentes / hoy',urgent.length,overdue.length?`${overdue.length} vencida(s)`:'Sin vencidas','tasks')}{metric(<WhatsAppIcon color="action"/>, 'Seguimientos',followups.length,'Seguimiento clínico y remarketing','tasks')}{metric(<ReceiptLongIcon color="action"/>, 'Cobros',collections.length,'Pendientes asignados','tasks')}{metric(<Inventory2Icon color={lowStock.length?'warning':'action'}/>, 'Inventario',lowStock.length,lowStock.length?'Producto(s) bajo mínimo':'Stock sin alertas','inventory')}</Box>{urgent.length===0&&followups.length===0&&collections.length===0&&lowStock.length===0&&<Alert icon={<CheckCircleOutlineIcon/>} severity="success">Todo al día. No hay pendientes operativos relevantes para vos.</Alert>}<Card variant="outlined"><CardContent><Stack direction={{xs:'column',md:'row'}} justifyContent="space-between" alignItems={{md:'center'}} spacing={2}><Box><Typography fontWeight={900}>Accesos rápidos</Typography><Typography variant="body2" color="text.secondary">Entrá directo a la acción que necesitás.</Typography></Box><Stack direction="row" spacing={1} flexWrap="wrap"><Button onClick={()=>onNavigate('tasks')}>CRM</Button><Button onClick={()=>onNavigate('procedures')}>Procedimientos</Button><Button onClick={()=>onNavigate('inventory')}>Inventario</Button>{role==='admin'&&<Button startIcon={<AccountBalanceWalletIcon/>} variant="outlined" onClick={()=>onNavigate('financial-analytics')}>Ver resumen financiero</Button>}</Stack></Stack></CardContent></Card></Stack>}
