import React,{useEffect,useMemo,useState}from'react';
import{Alert,Box,Button,Card,CardContent,Chip,Dialog,DialogActions,DialogContent,DialogTitle,Divider,Stack,TextField,Typography,IconButton,Tooltip}from'@mui/material';
import PaidIcon from'@mui/icons-material/Paid';
import LockIcon from'@mui/icons-material/Lock';
import EditIcon from'@mui/icons-material/Edit';
import DeleteOutlineIcon from'@mui/icons-material/DeleteOutline';
import RefreshIcon from'@mui/icons-material/Refresh';
import{supabase}from'./supabase.js';

const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
const fmt=d=>d?new Date(`${d}T12:00:00`).toLocaleDateString('es-CR'):'';
const iso=d=>d.toISOString().slice(0,10);
function currentWeek(){const d=new Date();const day=(d.getDay()+6)%7;const s=new Date(d);s.setDate(d.getDate()-day);const e=new Date(s);e.setDate(s.getDate()+6);return{start:iso(s),end:iso(e)}}

function TransferDialog({batch,direction,open,onClose,onSaved,organization}){
 const label=direction==='clinic_to_rodolfo'?'Clínica → Rodolfo':'Rodolfo → Clínica';
 const amount=direction==='clinic_to_rodolfo'?batch?.clinic_to_rodolfo_due_usd:batch?.rodolfo_to_clinic_due_usd;
 const[reference,setReference]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(open){setReference('');setError('')}},[open]);if(!batch)return null;
 const save=async()=>{setSaving(true);const{error:e}=await supabase.rpc('set_reconciliation_transfer_status',{p_organization_id:organization.id,p_reconciliation_id:batch.id,p_direction:direction,p_paid:true,p_reference:reference});if(e){console.error(e);setError('No se pudo registrar el pago.');setSaving(false);return}await onSaved();setSaving(false);onClose()};
 return <Dialog open={open} onClose={saving?undefined:onClose} fullWidth maxWidth="xs"><DialogTitle>Registrar transferencia</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{error&&<Alert severity="error">{error}</Alert>}<Alert severity="info">{label} · {money(amount)}</Alert><TextField label="Referencia / comprobante" value={reference} onChange={e=>setReference(e.target.value)} fullWidth/></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancelar</Button><Button variant="contained" onClick={save} disabled={saving}>{saving?'Guardando…':'Marcar como pagado'}</Button></DialogActions></Dialog>
}

function EditBatchDialog({batch,open,onClose,onSaved,organization}){
 const[start,setStart]=useState(''),[end,setEnd]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(open&&batch){setStart(batch.week_start);setEnd(batch.week_end);setError('')}},[open,batch]);if(!batch)return null;
 const save=async()=>{setSaving(true);setError('');const{data,error:e}=await supabase.rpc('recalculate_weekly_reconciliation',{p_organization_id:organization.id,p_reconciliation_id:batch.id,p_week_start:start,p_week_end:end});if(e){console.error(e);setError(e.message?.includes('already exists')?'Ya existe otra conciliación activa para ese período.':'No se pudo recalcular la conciliación.');setSaving(false);return}await onSaved(data);setSaving(false);onClose()};
 return <Dialog open={open} onClose={saving?undefined:onClose} fullWidth maxWidth="sm"><DialogTitle>Editar conciliación abierta</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{error&&<Alert severity="error">{error}</Alert>}<Alert severity="warning">Al recalcular se vuelven a buscar todos los pagos elegibles del período. Si alguna transferencia ya estaba marcada como pagada, se reiniciará porque los montos pueden haber cambiado.</Alert><Stack direction={{xs:'column',sm:'row'}} spacing={2}><TextField fullWidth label="Inicio" type="date" value={start} onChange={e=>setStart(e.target.value)} InputLabelProps={{shrink:true}}/><TextField fullWidth label="Fin" type="date" value={end} onChange={e=>setEnd(e.target.value)} InputLabelProps={{shrink:true}}/></Stack></Stack></DialogContent><DialogActions><Button onClick={onClose} disabled={saving}>Cancelar</Button><Button startIcon={<RefreshIcon/>} variant="contained" onClick={save} disabled={saving}>{saving?'Recalculando…':'Guardar y recalcular'}</Button></DialogActions></Dialog>
}

function VoidBatchDialog({batch,open,onClose,onSaved,organization,userId}){
 const[reason,setReason]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(open){setReason('');setError('')}},[open]);if(!batch)return null;
 const save=async()=>{if(!reason.trim())return setError('Indicá el motivo de la anulación.');setSaving(true);const{data,error:e}=await supabase.rpc('void_weekly_reconciliation',{p_organization_id:organization.id,p_reconciliation_id:batch.id,p_reason:reason,p_voided_by:userId});if(e){console.error(e);setError(e.message?.includes('Closed')?'Una conciliación cerrada no puede anularse.':'No se pudo anular la conciliación.');setSaving(false);return}await onSaved(data);setSaving(false);onClose()};
 return <Dialog open={open} onClose={saving?undefined:onClose} fullWidth maxWidth="sm"><DialogTitle>Anular conciliación</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{error&&<Alert severity="error">{error}</Alert>}<Alert severity="warning">La conciliación no se borra. Quedará en el histórico como anulada y sus pagos volverán a quedar disponibles para una nueva conciliación.</Alert><TextField label="Motivo de anulación" value={reason} onChange={e=>setReason(e.target.value)} multiline minRows={3} required/></Stack></DialogContent><DialogActions><Button onClick={onClose} disabled={saving}>Cancelar</Button><Button color="error" variant="contained" onClick={save} disabled={saving}>{saving?'Anulando…':'Anular conciliación'}</Button></DialogActions></Dialog>
}

export default function ReconciliationScreen({organization,userId,role}){
 const w=currentWeek();const[start,setStart]=useState(w.start),[end,setEnd]=useState(w.end),[batches,setBatches]=useState([]),[selected,setSelected]=useState(null),[transfer,setTransfer]=useState(null),[editing,setEditing]=useState(false),[voiding,setVoiding]=useState(false),[error,setError]=useState(''),[creating,setCreating]=useState(false);
 const load=async(preferred)=>{const{data,error:e}=await supabase.from('reconciliation_batches').select('*').eq('organization_id',organization.id).order('week_start',{ascending:false});if(e)setError('No se pudieron cargar las conciliaciones.');else{setBatches(data||[]);const wanted=preferred?.id||selected?.id;setSelected(wanted?(data||[]).find(x=>x.id===wanted)||null:(data||[]).find(x=>x.status!=='voided')||(data||[])[0]||null)}};
 useEffect(()=>{load()},[organization.id]);
 const canClose=selected&&selected.status==='open'&&['paid','not_required'].includes(selected.clinic_to_rodolfo_status)&&['paid','not_required'].includes(selected.rodolfo_to_clinic_status);
 const create=async()=>{if(role!=='admin')return;setCreating(true);setError('');const{data,error:e}=await supabase.rpc('create_weekly_reconciliation',{p_organization_id:organization.id,p_week_start:start,p_week_end:end,p_created_by:userId});if(e){console.error(e);setError(e.message?.includes('already exists')?'Ya existe una conciliación para ese período.':'No se pudo generar la conciliación.');setCreating(false);return}await load(data);setSelected(data);setCreating(false)};
 const recalc=async()=>{if(!selected||selected.status!=='open')return;const{data,error:e}=await supabase.rpc('recalculate_weekly_reconciliation',{p_organization_id:organization.id,p_reconciliation_id:selected.id,p_week_start:selected.week_start,p_week_end:selected.week_end});if(e){console.error(e);setError('No se pudo recalcular la conciliación.');return}await load(data);setSelected(data)};
 const close=async()=>{const{data,error:e}=await supabase.rpc('close_weekly_reconciliation',{p_organization_id:organization.id,p_reconciliation_id:selected.id,p_closed_by:userId});if(e){console.error(e);setError('No se pudo cerrar. Verificá que ambas transferencias estén completas.');return}await load(data);setSelected(data)};
 const statusLabel=s=>s==='paid'?'Pagado':s==='not_required'?'No corresponde':'Pendiente';
 const cards=useMemo(()=>selected?[['Ingresos conciliables',selected.eligible_revenue_usd],['Clínica → Rodolfo',selected.clinic_to_rodolfo_due_usd],['Rodolfo → Clínica',selected.rodolfo_to_clinic_due_usd],['IVA Rodolfo',selected.vat_cost_usd],['Comisiones bancarias',selected.processor_fees_usd],['Costo productos',selected.product_cost_usd],['Margen Rodolfo',selected.rodolfo_margin_usd]]:[],[selected]);
 const stateLabel=s=>s==='closed'?'Cerrada':s==='voided'?'Anulada':'Abierta';
 return <Stack spacing={3}><Box><Typography variant="h4" fontWeight={800}>Conciliación</Typography><Typography color="text.secondary">Cierre semanal entre clínica y Rodolfo con 70/30, IVA, comisiones y costos de producto.</Typography></Box>{error&&<Alert severity="error">{error}</Alert>}
 <Card variant="outlined"><CardContent><Stack direction={{xs:'column',md:'row'}} spacing={2} alignItems={{md:'center'}}><TextField label="Inicio" type="date" value={start} onChange={e=>setStart(e.target.value)} InputLabelProps={{shrink:true}}/><TextField label="Fin" type="date" value={end} onChange={e=>setEnd(e.target.value)} InputLabelProps={{shrink:true}}/><Button variant="contained" onClick={create} disabled={creating||role!=='admin'}>{creating?'Generando…':'Generar conciliación'}</Button></Stack></CardContent></Card>
 {selected&&<><Stack direction={{xs:'column',md:'row'}} spacing={2} flexWrap="wrap">{cards.map(([label,val])=><Card key={label} variant="outlined" sx={{flex:'1 1 180px'}}><CardContent><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h6" fontWeight={800}>{money(val)}</Typography></CardContent></Card>)}</Stack>
 <Card variant="outlined"><CardContent><Stack spacing={2}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" spacing={1}><Box><Typography fontWeight={800}>Semana {fmt(selected.week_start)} – {fmt(selected.week_end)}</Typography><Typography variant="body2" color="text.secondary">Estado: {stateLabel(selected.status)}</Typography>{selected.status==='voided'&&selected.void_reason&&<Typography variant="caption" color="error">Motivo: {selected.void_reason}</Typography>}</Box><Stack direction="row" spacing={1} alignItems="center"><Chip label={selected.status==='closed'?'Conciliada':selected.status==='voided'?'Anulada':'Pendiente de cierre'} color={selected.status==='closed'?'success':selected.status==='voided'?'error':'warning'}/>{selected.status==='open'&&role==='admin'&&<><Tooltip title="Editar período y recalcular"><IconButton onClick={()=>setEditing(true)}><EditIcon/></IconButton></Tooltip><Tooltip title="Recalcular ahora"><IconButton onClick={recalc}><RefreshIcon/></IconButton></Tooltip><Tooltip title="Anular conciliación"><IconButton color="error" onClick={()=>setVoiding(true)}><DeleteOutlineIcon/></IconButton></Tooltip></>}</Stack></Stack>
 {selected.status!=='voided'&&<><Divider/><TransferRow label="Clínica → Rodolfo" amount={selected.clinic_to_rodolfo_due_usd} status={selected.clinic_to_rodolfo_status} reference={selected.clinic_to_rodolfo_reference} onPay={()=>setTransfer('clinic_to_rodolfo')} locked={selected.status==='closed'} statusLabel={statusLabel}/><Divider/><TransferRow label="Rodolfo → Clínica" amount={selected.rodolfo_to_clinic_due_usd} status={selected.rodolfo_to_clinic_status} reference={selected.rodolfo_to_clinic_reference} onPay={()=>setTransfer('rodolfo_to_clinic')} locked={selected.status==='closed'} statusLabel={statusLabel}/></>}
 {selected.status==='open'&&<><Divider/><Button startIcon={<LockIcon/>} variant="contained" color="success" disabled={!canClose} onClick={close}>Conciliar semana</Button>{!canClose&&<Typography variant="caption" color="text.secondary">Solo se puede cerrar cuando ambas transferencias estén pagadas o no correspondan.</Typography>}</>}
 </Stack></CardContent></Card></>}
 <Card variant="outlined"><CardContent sx={{p:0}}>{batches.length===0?<Box p={3}><Typography color="text.secondary">Todavía no hay conciliaciones.</Typography></Box>:batches.map((b,i)=><Box key={b.id}>{i>0&&<Divider/>}<Box p={2} onClick={()=>setSelected(b)} sx={{cursor:'pointer',opacity:b.status==='voided'?.65:1,'&:hover':{bgcolor:'action.hover'}}}><Stack direction="row" justifyContent="space-between" spacing={2}><Box><Typography fontWeight={700}>{fmt(b.week_start)} – {fmt(b.week_end)}</Typography><Typography variant="caption" color="text.secondary">Ingresos {money(b.eligible_revenue_usd)} · Margen {money(b.rodolfo_margin_usd)}</Typography></Box><Chip size="small" label={stateLabel(b.status)} color={b.status==='closed'?'success':b.status==='voided'?'error':'default'}/></Stack></Box></Box>)}</CardContent></Card>
 <TransferDialog batch={selected} direction={transfer} open={Boolean(transfer)} onClose={()=>setTransfer(null)} onSaved={load} organization={organization}/>
 <EditBatchDialog batch={selected} open={editing} onClose={()=>setEditing(false)} onSaved={async data=>{await load(data);setSelected(data)}} organization={organization}/>
 <VoidBatchDialog batch={selected} open={voiding} onClose={()=>setVoiding(false)} onSaved={async data=>{await load(data);setSelected(data)}} organization={organization} userId={userId}/>
 </Stack>
}

function TransferRow({label,amount,status,reference,onPay,locked,statusLabel}){return <Stack direction="row" justifyContent="space-between" alignItems="center" spacing={2}><Box><Typography fontWeight={700}>{label}</Typography><Typography variant="body2" color="text.secondary">{money(amount)}{reference?` · Ref. ${reference}`:''}</Typography></Box><Stack direction="row" spacing={1} alignItems="center"><Chip size="small" label={statusLabel(status)} color={status==='paid'?'success':status==='pending'?'warning':'default'}/>{status==='pending'&&!locked&&<Tooltip title="Registrar pago"><IconButton color="success" onClick={onPay}><PaidIcon/></IconButton></Tooltip>}</Stack></Stack>}
