import React,{useEffect,useMemo,useState}from'react';
import{Alert,Box,Button,Card,CardContent,Chip,Dialog,DialogActions,DialogContent,DialogTitle,Divider,Stack,TextField,Typography}from'@mui/material';
import PaidIcon from'@mui/icons-material/Paid';
import LockIcon from'@mui/icons-material/Lock';
import{IconButton,Tooltip}from'@mui/material';
import{supabase}from'./supabase.js';

const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n||0));
const fmt=d=>d?new Date(`${d}T12:00:00`).toLocaleDateString('es-CR'):'';
const iso=d=>d.toISOString().slice(0,10);
function currentWeek(){const d=new Date();const day=(d.getDay()+6)%7;const s=new Date(d);s.setDate(d.getDate()-day);const e=new Date(s);e.setDate(s.getDate()+6);return{start:iso(s),end:iso(e)}}

function TransferDialog({batch,direction,open,onClose,onSaved,organization}){
 const label=direction==='clinic_to_rodolfo'?'Clínica → Rodolfo':'Rodolfo → Clínica';
 const amount=direction==='clinic_to_rodolfo'?batch?.clinic_to_rodolfo_due_usd:batch?.rodolfo_to_clinic_due_usd;
 const[reference,setReference]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(open){setReference('');setError('')}},[open]);if(!batch)return null;
 const save=async()=>{setSaving(true);const{error:e}=await supabase.rpc('set_reconciliation_transfer_status',{p_organization_id:organization.id,p_reconciliation_id:batch.id,p_direction:direction,p_paid:true,p_reference:reference});if(e){console.error(e);setError('No se pudo registrar el pago.');setSaving(false);return}await onSaved();setSaving(false);onClose()};
 return <Dialog open={open} onClose={saving?undefined:onClose} fullWidth maxWidth="xs"><DialogTitle>Registrar transferencia</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{error&&<Alert severity="error">{error}</Alert>}<Alert severity="info">{label} · {money(amount)}</Alert><TextField label="Referencia / comprobante" value={reference} onChange={e=>setReference(e.target.value)} fullWidth/></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancelar</Button><Button variant="contained" onClick={save} disabled={saving}>{saving?'Guardando…':'Marcar como pagado'}</Button></DialogActions></Dialog>
}

export default function ReconciliationScreen({organization,userId,role}){
 const w=currentWeek();const[start,setStart]=useState(w.start),[end,setEnd]=useState(w.end),[batches,setBatches]=useState([]),[selected,setSelected]=useState(null),[transfer,setTransfer]=useState(null),[error,setError]=useState(''),[creating,setCreating]=useState(false);
 const load=async()=>{const{data,error:e}=await supabase.from('reconciliation_batches').select('*').eq('organization_id',organization.id).order('week_start',{ascending:false});if(e)setError('No se pudieron cargar las conciliaciones.');else{setBatches(data||[]);setSelected(cur=>cur?(data||[]).find(x=>x.id===cur.id)||cur:(data||[])[0]||null)}};
 useEffect(()=>{load()},[organization.id]);
 const canClose=selected&&selected.status==='open'&&['paid','not_required'].includes(selected.clinic_to_rodolfo_status)&&['paid','not_required'].includes(selected.rodolfo_to_clinic_status);
 const create=async()=>{if(role!=='admin')return;setCreating(true);setError('');const{data,error:e}=await supabase.rpc('create_weekly_reconciliation',{p_organization_id:organization.id,p_week_start:start,p_week_end:end,p_created_by:userId});if(e){console.error(e);setError(e.message?.includes('already exists')?'Ya existe una conciliación para ese período.':'No se pudo generar la conciliación.');setCreating(false);return}await load();setSelected(data);setCreating(false)};
 const close=async()=>{const{data,error:e}=await supabase.rpc('close_weekly_reconciliation',{p_organization_id:organization.id,p_reconciliation_id:selected.id,p_closed_by:userId});if(e){console.error(e);setError('No se pudo cerrar. Verificá que ambas transferencias estén completas.');return}await load();setSelected(data)};
 const statusLabel=s=>s==='paid'?'Pagado':s==='not_required'?'No corresponde':'Pendiente';
 const cards=useMemo(()=>selected?[['Ingresos conciliables',selected.eligible_revenue_usd],['Clínica → Rodolfo',selected.clinic_to_rodolfo_due_usd],['Rodolfo → Clínica',selected.rodolfo_to_clinic_due_usd],['IVA Rodolfo',selected.vat_cost_usd],['Comisiones bancarias',selected.processor_fees_usd],['Costo productos',selected.product_cost_usd],['Margen Rodolfo',selected.rodolfo_margin_usd]]:[],[selected]);
 return <Stack spacing={3}><Box><Typography variant="h4" fontWeight={800}>Conciliación</Typography><Typography color="text.secondary">Cierre semanal entre clínica y Rodolfo con 70/30, IVA, comisiones y costos de producto.</Typography></Box>{error&&<Alert severity="error">{error}</Alert>}
 <Card variant="outlined"><CardContent><Stack direction={{xs:'column',md:'row'}} spacing={2} alignItems={{md:'center'}}><TextField label="Inicio" type="date" value={start} onChange={e=>setStart(e.target.value)} InputLabelProps={{shrink:true}}/><TextField label="Fin" type="date" value={end} onChange={e=>setEnd(e.target.value)} InputLabelProps={{shrink:true}}/><Button variant="contained" onClick={create} disabled={creating||role!=='admin'}>{creating?'Generando…':'Generar conciliación'}</Button></Stack></CardContent></Card>
 {selected&&<><Stack direction={{xs:'column',md:'row'}} spacing={2} flexWrap="wrap">{cards.map(([label,val])=><Card key={label} variant="outlined" sx={{flex:'1 1 180px'}}><CardContent><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h6" fontWeight={800}>{money(val)}</Typography></CardContent></Card>)}</Stack>
 <Card variant="outlined"><CardContent><Stack spacing={2}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" spacing={1}><Box><Typography fontWeight={800}>Semana {fmt(selected.week_start)} – {fmt(selected.week_end)}</Typography><Typography variant="body2" color="text.secondary">Estado: {selected.status==='closed'?'Cerrada':'Abierta'}</Typography></Box><Chip label={selected.status==='closed'?'Conciliada':'Pendiente de cierre'} color={selected.status==='closed'?'success':'warning'}/></Stack><Divider/>
 <TransferRow label="Clínica → Rodolfo" amount={selected.clinic_to_rodolfo_due_usd} status={selected.clinic_to_rodolfo_status} reference={selected.clinic_to_rodolfo_reference} onPay={()=>setTransfer('clinic_to_rodolfo')} locked={selected.status==='closed'} statusLabel={statusLabel}/>
 <Divider/><TransferRow label="Rodolfo → Clínica" amount={selected.rodolfo_to_clinic_due_usd} status={selected.rodolfo_to_clinic_status} reference={selected.rodolfo_to_clinic_reference} onPay={()=>setTransfer('rodolfo_to_clinic')} locked={selected.status==='closed'} statusLabel={statusLabel}/>
 {selected.status==='open'&&<><Divider/><Button startIcon={<LockIcon/>} variant="contained" color="success" disabled={!canClose} onClick={close}>Conciliar semana</Button>{!canClose&&<Typography variant="caption" color="text.secondary">Solo se puede cerrar cuando ambas transferencias estén pagadas o no correspondan.</Typography>}</>}
 </Stack></CardContent></Card></>}
 <Card variant="outlined"><CardContent sx={{p:0}}>{batches.length===0?<Box p={3}><Typography color="text.secondary">Todavía no hay conciliaciones.</Typography></Box>:batches.map((b,i)=><Box key={b.id}>{i>0&&<Divider/>}<Box p={2} onClick={()=>setSelected(b)} sx={{cursor:'pointer','&:hover':{bgcolor:'action.hover'}}}><Stack direction="row" justifyContent="space-between" spacing={2}><Box><Typography fontWeight={700}>{fmt(b.week_start)} – {fmt(b.week_end)}</Typography><Typography variant="caption" color="text.secondary">Ingresos {money(b.eligible_revenue_usd)} · Margen {money(b.rodolfo_margin_usd)}</Typography></Box><Chip size="small" label={b.status==='closed'?'Cerrada':'Abierta'} color={b.status==='closed'?'success':'default'}/></Stack></Box></Box>)}</CardContent></Card>
 <TransferDialog batch={selected} direction={transfer} open={Boolean(transfer)} onClose={()=>setTransfer(null)} onSaved={load} organization={organization}/></Stack>
}

function TransferRow({label,amount,status,reference,onPay,locked,statusLabel}){return <Stack direction="row" justifyContent="space-between" alignItems="center" spacing={2}><Box><Typography fontWeight={700}>{label}</Typography><Typography variant="body2" color="text.secondary">{money(amount)}{reference?` · Ref. ${reference}`:''}</Typography></Box><Stack direction="row" spacing={1} alignItems="center"><Chip size="small" label={statusLabel(status)} color={status==='paid'?'success':status==='pending'?'warning':'default'}/>{status==='pending'&&!locked&&<Tooltip title="Registrar pago"><IconButton color="success" onClick={onPay}><PaidIcon/></IconButton></Tooltip>}</Stack></Stack>}
