import React,{useEffect,useMemo,useState}from'react';
import{Alert,Box,Button,Card,CardContent,Chip,Dialog,DialogActions,DialogContent,DialogTitle,Divider,IconButton,Stack,TextField,Tooltip,Typography}from'@mui/material';
import PaidIcon from'@mui/icons-material/Paid';
import LockIcon from'@mui/icons-material/Lock';
import EditIcon from'@mui/icons-material/Edit';
import DeleteOutlineIcon from'@mui/icons-material/DeleteOutline';
import RefreshIcon from'@mui/icons-material/Refresh';
import{supabase}from'./supabase.js';

const money=(n,c='USD')=>new Intl.NumberFormat(c==='CRC'?'es-CR':'en-US',{style:'currency',currency:c}).format(Number(n||0));
const fmt=d=>d?new Date(`${d}T12:00:00`).toLocaleDateString('es-CR'):'';
const iso=d=>d.toISOString().slice(0,10);
function currentWeek(){const d=new Date();const day=(d.getDay()+6)%7;const s=new Date(d);s.setDate(d.getDate()-day);const e=new Date(s);e.setDate(s.getDate()+6);return{start:iso(s),end:iso(e)}}

function TransferDialog({transfer,open,onClose,onSaved,organization}){
 const label=transfer?.direction==='clinic_to_rodolfo'?'Clínica → Rodolfo':'Rodolfo → Clínica';
 const[reference,setReference]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(open){setReference(transfer?.reference||'');setError('')}},[open,transfer]);if(!transfer)return null;
 const save=async()=>{setSaving(true);const{error:e}=await supabase.rpc('set_reconciliation_transfer_status',{p_organization_id:organization.id,p_reconciliation_id:transfer.reconciliation_id,p_direction:transfer.direction,p_currency:transfer.currency,p_paid:true,p_reference:reference});if(e){console.error(e);setError('No se pudo registrar la transferencia.');setSaving(false);return}await onSaved();setSaving(false);onClose()};
 return <Dialog open={open} onClose={saving?undefined:onClose} fullWidth maxWidth="xs"><DialogTitle>Registrar transferencia</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{error&&<Alert severity="error">{error}</Alert>}<Alert severity="info">{label} · {transfer.currency} · {money(transfer.amount,transfer.currency)}</Alert><TextField label="Referencia / comprobante" value={reference} onChange={e=>setReference(e.target.value)} fullWidth/></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancelar</Button><Button variant="contained" onClick={save} disabled={saving}>{saving?'Guardando…':'Marcar como pagado'}</Button></DialogActions></Dialog>
}

function VoidDialog({batch,open,onClose,onSaved,organization,userId}){
 const[reason,setReason]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(open){setReason('');setError('')}},[open]);if(!batch)return null;
 const save=async()=>{if(!reason.trim())return setError('Indicá el motivo de la anulación.');setSaving(true);const{error:e}=await supabase.rpc('void_weekly_reconciliation',{p_organization_id:organization.id,p_reconciliation_id:batch.id,p_reason:reason.trim(),p_voided_by:userId});if(e){console.error(e);setError('No se pudo anular la conciliación.');setSaving(false);return}await onSaved();setSaving(false);onClose()};
 return <Dialog open={open} onClose={saving?undefined:onClose} fullWidth maxWidth="sm"><DialogTitle>Anular conciliación</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{error&&<Alert severity="error">{error}</Alert>}<Alert severity="warning">La conciliación quedará en el histórico como anulada y sus pagos volverán a quedar disponibles para una nueva conciliación, incluso si esta conciliación ya estaba cerrada.</Alert><TextField label="Motivo" value={reason} onChange={e=>setReason(e.target.value)} multiline minRows={3} required/></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancelar</Button><Button color="error" variant="contained" onClick={save} disabled={saving}>{saving?'Anulando…':'Anular conciliación'}</Button></DialogActions></Dialog>
}

function EditRangeDialog({batch,open,onClose,onSaved,organization}){
 const[start,setStart]=useState(''),[end,setEnd]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 useEffect(()=>{if(open&&batch){setStart(batch.week_start);setEnd(batch.week_end);setError('')}},[open,batch]);if(!batch)return null;
 const save=async()=>{setSaving(true);const{error:e}=await supabase.rpc('recalculate_weekly_reconciliation',{p_organization_id:organization.id,p_reconciliation_id:batch.id,p_week_start:start,p_week_end:end});if(e){console.error(e);setError(e.message?.includes('already exists')?'Ya existe otra conciliación activa para ese período.':'No se pudo recalcular la conciliación.');setSaving(false);return}await onSaved();setSaving(false);onClose()};
 return <Dialog open={open} onClose={saving?undefined:onClose} fullWidth maxWidth="xs"><DialogTitle>Editar período</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{error&&<Alert severity="error">{error}</Alert>}<Alert severity="info">Al guardar se recalcularán los pagos y las transferencias. Si alguna transferencia estaba marcada como pagada volverá a pendiente porque el monto puede cambiar.</Alert><TextField label="Inicio" type="date" value={start} onChange={e=>setStart(e.target.value)} InputLabelProps={{shrink:true}}/><TextField label="Fin" type="date" value={end} onChange={e=>setEnd(e.target.value)} InputLabelProps={{shrink:true}}/></Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancelar</Button><Button variant="contained" onClick={save} disabled={saving}>{saving?'Guardando…':'Guardar y recalcular'}</Button></DialogActions></Dialog>
}

export default function ReconciliationScreen({organization,userId,role}){
 const w=currentWeek();const[start,setStart]=useState(w.start),[end,setEnd]=useState(w.end),[batches,setBatches]=useState([]),[transfers,setTransfers]=useState([]),[selected,setSelected]=useState(null),[transfer,setTransfer]=useState(null),[voiding,setVoiding]=useState(null),[editing,setEditing]=useState(null),[error,setError]=useState(''),[creating,setCreating]=useState(false);
 const load=async()=>{const[b,t]=await Promise.all([supabase.from('reconciliation_batches').select('*').eq('organization_id',organization.id).order('week_start',{ascending:false}),supabase.from('reconciliation_transfers').select('*').eq('organization_id',organization.id).order('currency')]);if(b.error||t.error){setError('No se pudieron cargar las conciliaciones.');return}setBatches(b.data||[]);setTransfers(t.data||[]);setSelected(cur=>cur?(b.data||[]).find(x=>x.id===cur.id)||null:(b.data||[])[0]||null)};
 useEffect(()=>{load()},[organization.id]);
 const selectedTransfers=useMemo(()=>selected?transfers.filter(t=>t.reconciliation_id===selected.id):[],[transfers,selected]);
 const canClose=selected&&selected.status==='open'&&selectedTransfers.length>0&&selectedTransfers.every(t=>['paid','not_required'].includes(t.status));
 const create=async()=>{if(role!=='admin')return;setCreating(true);setError('');const{data,error:e}=await supabase.rpc('create_weekly_reconciliation',{p_organization_id:organization.id,p_week_start:start,p_week_end:end,p_created_by:userId});if(e){console.error(e);setError(e.message?.includes('already exists')?'Ya existe una conciliación para ese período.':'No se pudo generar la conciliación.');setCreating(false);return}await load();setSelected(data);setCreating(false)};
 const recalc=async()=>{if(!selected||selected.status!=='open')return;const{data,error:e}=await supabase.rpc('recalculate_weekly_reconciliation',{p_organization_id:organization.id,p_reconciliation_id:selected.id,p_week_start:null,p_week_end:null});if(e){console.error(e);setError('No se pudo recalcular la conciliación.');return}await load();setSelected(data)};
 const close=async()=>{const{data,error:e}=await supabase.rpc('close_weekly_reconciliation',{p_organization_id:organization.id,p_reconciliation_id:selected.id,p_closed_by:userId});if(e){console.error(e);setError('No se pudo cerrar. Verificá que todas las transferencias USD y CRC estén completas.');return}await load();setSelected(data)};
 const statusLabel=s=>s==='paid'?'Pagado':s==='not_required'?'No corresponde':'Pendiente';
 const cards=useMemo(()=>selected?[['Cobros USD',money(selected.eligible_revenue_usd,'USD')],['Cobros CRC',money(selected.eligible_revenue_crc,'CRC')],['IVA USD',money(selected.vat_cost_usd,'USD')],['IVA CRC',money(selected.vat_cost_crc,'CRC')],['Comisiones USD',money(selected.processor_fees_usd,'USD')],['Comisiones CRC',money(selected.processor_fees_crc,'CRC')],['Costo productos',money(selected.product_cost_usd,'USD')],['Margen estimado equiv. USD',money(selected.rodolfo_margin_usd,'USD')]]:[],[selected]);
 const batchLabel=b=>b.status==='closed'?'Cerrada':b.status==='voided'?'Anulada':'Abierta';
 return <Stack spacing={3}><Box><Typography variant="h4" fontWeight={800}>Conciliación</Typography><Typography color="text.secondary">Los cobros y transferencias se mantienen separados por moneda. USD y CRC no se mezclan para el pago entre clínica y Rodolfo.</Typography></Box>{error&&<Alert severity="error">{error}</Alert>}
 <Card variant="outlined"><CardContent><Stack direction={{xs:'column',md:'row'}} spacing={2} alignItems={{md:'center'}}><TextField label="Inicio" type="date" value={start} onChange={e=>setStart(e.target.value)} InputLabelProps={{shrink:true}}/><TextField label="Fin" type="date" value={end} onChange={e=>setEnd(e.target.value)} InputLabelProps={{shrink:true}}/><Button variant="contained" onClick={create} disabled={creating||role!=='admin'}>{creating?'Generando…':'Generar conciliación'}</Button></Stack></CardContent></Card>
 {selected&&<><Stack direction={{xs:'column',md:'row'}} spacing={2} flexWrap="wrap">{cards.map(([label,val])=><Card key={label} variant="outlined" sx={{flex:'1 1 180px'}}><CardContent><Typography variant="caption" color="text.secondary">{label}</Typography><Typography variant="h6" fontWeight={800}>{val}</Typography></CardContent></Card>)}</Stack>
 <Card variant="outlined"><CardContent><Stack spacing={2}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" spacing={1}><Box><Typography fontWeight={800}>Semana {fmt(selected.week_start)} – {fmt(selected.week_end)}</Typography><Typography variant="body2" color="text.secondary">Estado: {batchLabel(selected)}</Typography>{selected.status==='voided'&&selected.void_reason&&<Typography variant="caption" color="error">Motivo: {selected.void_reason}</Typography>}</Box><Stack direction="row" spacing={.5} alignItems="center"><Chip label={batchLabel(selected)} color={selected.status==='closed'?'success':selected.status==='voided'?'error':'warning'}/>{selected.status==='open'&&<><Tooltip title="Editar período"><IconButton onClick={()=>setEditing(selected)}><EditIcon/></IconButton></Tooltip><Tooltip title="Recalcular"><IconButton onClick={recalc}><RefreshIcon/></IconButton></Tooltip></>} {selected.status!=='voided'&&<Tooltip title={selected.status==='closed'?'Anular conciliación cerrada':'Anular conciliación'}><IconButton color="error" onClick={()=>setVoiding(selected)}><DeleteOutlineIcon/></IconButton></Tooltip>}</Stack></Stack><Divider/>
 <Typography fontWeight={800}>Transferencias por moneda</Typography>{selectedTransfers.length===0?<Alert severity="info">Esta conciliación es anterior al esquema por moneda. Si está abierta, recalculala para generar las transferencias USD y CRC.</Alert>:<Stack spacing={1.5}>{selectedTransfers.map(t=><TransferRow key={t.id} transfer={t} onPay={()=>setTransfer(t)} locked={selected.status!=='open'} statusLabel={statusLabel}/>)}</Stack>}
 {selected.status==='open'&&<><Divider/><Button startIcon={<LockIcon/>} variant="contained" color="success" disabled={!canClose} onClick={close}>Conciliar semana</Button>{!canClose&&<Typography variant="caption" color="text.secondary">Solo se puede cerrar cuando todas las transferencias requeridas, tanto USD como CRC, estén pagadas.</Typography>}</>}
 </Stack></CardContent></Card></>}
 <Card variant="outlined"><CardContent sx={{p:0}}>{batches.length===0?<Box p={3}><Typography color="text.secondary">Todavía no hay conciliaciones.</Typography></Box>:batches.map((b,i)=><Box key={b.id}>{i>0&&<Divider/>}<Box p={2} onClick={()=>setSelected(b)} sx={{cursor:'pointer','&:hover':{bgcolor:'action.hover'}}}><Stack direction="row" justifyContent="space-between" spacing={2}><Box><Typography fontWeight={700}>{fmt(b.week_start)} – {fmt(b.week_end)}</Typography><Typography variant="caption" color="text.secondary">USD {money(b.eligible_revenue_usd,'USD')} · CRC {money(b.eligible_revenue_crc,'CRC')}</Typography></Box><Chip size="small" label={batchLabel(b)} color={b.status==='closed'?'success':b.status==='voided'?'error':'default'}/></Stack></Box></Box>)}</CardContent></Card>
 <TransferDialog transfer={transfer} open={Boolean(transfer)} onClose={()=>setTransfer(null)} onSaved={load} organization={organization}/><VoidDialog batch={voiding} open={Boolean(voiding)} onClose={()=>setVoiding(null)} onSaved={load} organization={organization} userId={userId}/><EditRangeDialog batch={editing} open={Boolean(editing)} onClose={()=>setEditing(null)} onSaved={load} organization={organization}/></Stack>
}

function TransferRow({transfer,onPay,locked,statusLabel}){const label=transfer.direction==='clinic_to_rodolfo'?'Clínica → Rodolfo':'Rodolfo → Clínica';return <Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" alignItems={{sm:'center'}} spacing={1}><Box><Typography fontWeight={700}>{label} · {transfer.currency}</Typography><Typography variant="body2" color="text.secondary">{money(transfer.amount,transfer.currency)}{transfer.reference?` · Ref. ${transfer.reference}`:''}</Typography></Box><Stack direction="row" spacing={1} alignItems="center"><Chip size="small" label={statusLabel(transfer.status)} color={transfer.status==='paid'?'success':transfer.status==='pending'?'warning':'default'}/>{transfer.status==='pending'&&!locked&&<Tooltip title="Registrar pago"><IconButton color="success" onClick={onPay}><PaidIcon/></IconButton></Tooltip>}</Stack></Stack>}
