import React,{useEffect,useMemo,useState}from'react'
import{Alert,Box,Button,Card,CardContent,Checkbox,Chip,Dialog,DialogActions,DialogContent,DialogTitle,Divider,FormControl,IconButton,InputLabel,MenuItem,Select,Stack,Tab,Tabs,TextField,Tooltip,Typography}from'@mui/material'
import EditIcon from'@mui/icons-material/Edit'
import ArchiveOutlinedIcon from'@mui/icons-material/ArchiveOutlined'
import RestoreIcon from'@mui/icons-material/Restore'
import ArrowForwardIcon from'@mui/icons-material/ArrowForward'
import PaidIcon from'@mui/icons-material/Paid'
import WhatsAppIcon from'@mui/icons-material/WhatsApp'
import ShoppingCartOutlinedIcon from'@mui/icons-material/ShoppingCartOutlined'
import PersonOutlineIcon from'@mui/icons-material/PersonOutline'
import{ supabase }from'./supabase.js'

const today=()=>new Date().toISOString().slice(0,10)
const fmt=d=>d?new Date(d).toLocaleDateString('es-CR'):''
const dayKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`}
const normalizeWhatsApp=phone=>{let d=String(phone||'').replace(/\D/g,'');if(d.startsWith('00'))d=d.slice(2);if(d.length===8)d=`506${d}`;return d}
function originFor(t){if(t.reference_type==='purchase_payment')return{section:'inventory',target:{type:'purchase',id:t.reference_id},label:'Ver compra'};if(t.reference_type==='product_low_stock')return{section:'products',target:{type:'product',id:t.reference_id},label:'Ver producto'};if(['procedure_followup','procedure','procedure_collection'].includes(t.reference_type))return{section:'procedures',target:{type:'procedure',id:t.reference_id},label:'Ver procedimiento'};return null}
function urgency(t){if(t.status!=='pending'||!t.due_at)return null;const k=dayKey(t.due_at),now=today();if(k<now)return{label:'Vencida',color:'error'};if(k===now)return{label:'Hoy',color:'warning'};return null}

export default function TasksScreen({organization,userId,onNavigate}){
 const[tab,setTab]=useState('pending'),[tasks,setTasks]=useState([]),[clients,setClients]=useState([]),[categories,setCategories]=useState([]),[categoryFilter,setCategoryFilter]=useState('all'),[dateFilter,setDateFilter]=useState('all'),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[error,setError]=useState('')
 const load=async()=>{const[t,c,cat]=await Promise.all([supabase.from('tasks').select('*').eq('organization_id',organization.id).order('due_at',{ascending:true,nullsFirst:false}).order('created_at',{ascending:false}),supabase.from('clients').select('id,full_name,phone').eq('organization_id',organization.id).order('full_name'),supabase.from('task_categories').select('*').eq('organization_id',organization.id).eq('active',true).order('name')]);if(t.error||c.error||cat.error)setError('No se pudo cargar el CRM.');else{setTasks(t.data||[]);setClients(c.data||[]);setCategories(cat.data||[])}}
 useEffect(()=>{load()},[organization.id])
 const clientById=useMemo(()=>Object.fromEntries(clients.map(c=>[c.id,c])),[clients])
 const categoryById=useMemo(()=>Object.fromEntries(categories.map(c=>[c.id,c])),[categories])
 const rows=useMemo(()=>{const now=today(),limit=new Date();limit.setDate(limit.getDate()+7);const limitKey=dayKey(limit);return tasks.filter(t=>{if(t.status!==tab)return false;if(categoryFilter!=='all'&&t.category_id!==categoryFilter)return false;if(dateFilter==='all')return true;if(dateFilter==='no_date')return!t.due_at;if(!t.due_at)return false;const k=dayKey(t.due_at);if(dateFilter==='overdue')return k<now;if(dateFilter==='today')return k===now;if(dateFilter==='next7')return k>now&&k<=limitKey;return true})},[tasks,tab,categoryFilter,dateFilter])
 const setStatus=async(t,status)=>{if(t.auto_generated&&['purchase_payment','procedure_collection'].includes(t.reference_type))return setError(t.reference_type==='purchase_payment'?'Las tareas de pago de compras se completan automáticamente al registrar el pago en Finanzas.':'Las tareas de cobro se completan automáticamente cuando el procedimiento queda pagado.');const patch={status,updated_at:new Date().toISOString()};if(status==='completed')patch.completed_at=new Date().toISOString();if(status==='archived')patch.archived_at=new Date().toISOString();if(status==='pending'){patch.completed_at=null;patch.archived_at=null}const{error:e}=await supabase.from('tasks').update(patch).eq('id',t.id).eq('organization_id',organization.id);if(e)return setError('No se pudo actualizar la tarea.');load()}
 const whatsapp=client=>{const n=normalizeWhatsApp(client?.phone);if(!n)return setError('Este cliente no tiene un teléfono válido registrado.');window.open(`https://wa.me/${n}`,'_blank','noopener,noreferrer')}
 return <Stack spacing={3}>
  <Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" spacing={2}><Box><Typography variant="h4" fontWeight={800}>CRM / Tareas</Typography><Typography color="text.secondary">Bandeja operativa de seguimientos, cobros, inventario, compras y tareas manuales.</Typography></Box><Button variant="contained" onClick={()=>{setEditing(null);setOpen(true)}}>+ Nueva tarea</Button></Stack>
  {error&&<Alert severity="error" onClose={()=>setError('')}>{error}</Alert>}
  <Stack direction={{xs:'column',md:'row'}} spacing={1.5}>
   <FormControl size="small" sx={{minWidth:190}}><InputLabel>Categoría</InputLabel><Select value={categoryFilter} label="Categoría" onChange={e=>setCategoryFilter(e.target.value)}><MenuItem value="all">Todas las categorías</MenuItem>{categories.map(c=><MenuItem key={c.id} value={c.id}>{c.name}</MenuItem>)}</Select></FormControl>
   <FormControl size="small" sx={{minWidth:190}}><InputLabel>Fecha</InputLabel><Select value={dateFilter} label="Fecha" onChange={e=>setDateFilter(e.target.value)}><MenuItem value="all">Todas las fechas</MenuItem><MenuItem value="overdue">Vencidas</MenuItem><MenuItem value="today">Hoy</MenuItem><MenuItem value="next7">Próximos 7 días</MenuItem><MenuItem value="no_date">Sin fecha</MenuItem></Select></FormControl>
  </Stack>
  <Tabs value={tab} onChange={(_,v)=>setTab(v)} variant="scrollable" scrollButtons="auto"><Tab value="pending" label={`Pendientes (${tasks.filter(t=>t.status==='pending').length})`}/><Tab value="completed" label={`Realizadas (${tasks.filter(t=>t.status==='completed').length})`}/><Tab value="archived" label={`Archivadas (${tasks.filter(t=>t.status==='archived').length})`}/></Tabs>
  <Card variant="outlined"><CardContent sx={{p:0}}>{rows.length===0?<Box p={3}><Typography color="text.secondary">No hay tareas para estos filtros.</Typography></Box>:rows.map((t,i)=>{const origin=originFor(t),isPurchase=t.reference_type==='purchase_payment',isCollection=t.reference_type==='procedure_collection',isLockedAuto=isPurchase||isCollection,isStock=t.reference_type==='product_low_stock',client=clientById[t.client_id],cat=categoryById[t.category_id],urgent=urgency(t);return <Box key={t.id}>{i>0&&<Divider/>}<Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" spacing={1} p={2}>
   <Stack direction="row" spacing={1.5} alignItems="flex-start"><Checkbox checked={t.status==='completed'} disabled={t.status==='archived'||isLockedAuto} onChange={()=>setStatus(t,t.status==='completed'?'pending':'completed')} sx={{mt:-.5}}/><Box>
    <Stack direction="row" spacing={1} alignItems="center" flexWrap="wrap"><Typography fontWeight={800}>{t.title}</Typography>{cat&&<Chip size="small" label={cat.name}/>} {t.auto_generated&&<Chip size="small" label="Automática" variant="outlined"/>}{urgent&&<Chip size="small" label={urgent.label} color={urgent.color}/>}</Stack>
    <Typography variant="body2" color="text.secondary">{t.due_at?`Vence ${fmt(t.due_at)}`:'Sin fecha límite'}{client?` · ${client.full_name}`:''}</Typography>{t.notes&&<Typography variant="body2" mt={.5}>{t.notes}</Typography>}
    <Stack direction="row" spacing={1} flexWrap="wrap" useFlexGap mt={1}>
     {isPurchase&&t.status==='pending'&&<Button size="small" variant="contained" startIcon={<PaidIcon/>} onClick={()=>onNavigate?.('finance',{type:'purchase_payment',id:t.reference_id})}>Registrar pago</Button>}
     {isCollection&&t.status==='pending'&&<Button size="small" variant="contained" startIcon={<PaidIcon/>} onClick={()=>onNavigate?.('payments',{type:'procedure_payment',id:t.reference_id})}>Registrar pago</Button>}
     {isStock&&t.status==='pending'&&<Button size="small" variant="contained" startIcon={<ShoppingCartOutlinedIcon/>} onClick={()=>onNavigate?.('inventory',null)}>Registrar compra</Button>}
     {client?.phone&&<Button size="small" variant="outlined" startIcon={<WhatsAppIcon/>} onClick={()=>whatsapp(client)}>WhatsApp</Button>}
     {client&&<Button size="small" startIcon={<PersonOutlineIcon/>} onClick={()=>onNavigate?.('clients',{type:'client',id:client.id})}>Ver cliente</Button>}
     {origin&&<Button size="small" endIcon={<ArrowForwardIcon/>} onClick={()=>onNavigate?.(origin.section,origin.target)}>{origin.label}</Button>}
    </Stack>
   </Box></Stack>
   <Stack direction="row" spacing={.5} alignItems="center">{t.status!=='archived'&&!t.auto_generated&&<Tooltip title="Editar"><IconButton size="small" onClick={()=>{setEditing(t);setOpen(true)}}><EditIcon fontSize="small"/></IconButton></Tooltip>}{t.status==='archived'?<Tooltip title="Restaurar"><IconButton size="small" onClick={()=>setStatus(t,'pending')}><RestoreIcon fontSize="small"/></IconButton></Tooltip>:!isLockedAuto&&<Tooltip title="Archivar"><IconButton size="small" onClick={()=>setStatus(t,'archived')}><ArchiveOutlinedIcon fontSize="small"/></IconButton></Tooltip>}</Stack>
  </Stack></Box>})}</CardContent></Card>
  <TaskDialog open={open} onClose={()=>{setOpen(false);setEditing(null)}} saved={load} editing={editing} organization={organization} userId={userId} clients={clients} categories={categories}/>
 </Stack>
}

function TaskDialog({open,onClose,saved,editing,organization,userId,clients,categories}){
 const blank={title:'',category_id:'',due_date:today(),client_id:'',notes:''};const[f,setF]=useState(blank),[error,setError]=useState('');
 useEffect(()=>{if(open){setError('');const general=categories.find(c=>c.slug==='general')||categories[0];setF(editing?{title:editing.title||'',category_id:editing.category_id||general?.id||'',due_date:editing.due_at?new Date(editing.due_at).toISOString().slice(0,10):'',client_id:editing.client_id||'',notes:editing.notes||''}:{...blank,category_id:general?.id||''})}},[open,editing,categories]);
 const save=async()=>{if(!f.title.trim())return setError('Escribí un título para la tarea.');if(!f.category_id)return setError('Seleccioná una categoría.');const category=categories.find(c=>c.id===f.category_id);const payload={title:f.title.trim(),category_id:f.category_id,category:category?.name||'General',due_at:f.due_date?`${f.due_date}T12:00:00`:null,client_id:f.client_id||null,notes:f.notes.trim()||null,updated_at:new Date().toISOString()};if(editing){const{error:e}=await supabase.from('tasks').update(payload).eq('id',editing.id).eq('organization_id',organization.id);if(e)return setError('No se pudo guardar la tarea.')}else{const{data,error:e}=await supabase.from('tasks').insert({...payload,organization_id:organization.id,status:'pending',auto_generated:false,created_by:userId,assigned_to:userId}).select('id').single();if(e)return setError('No se pudo guardar la tarea.');const{error:a}=await supabase.from('task_assignees').insert({organization_id:organization.id,task_id:data.id,user_id:userId,assigned_by:userId});if(a)console.error('No se pudo registrar responsable de la tarea',a)}await saved();onClose()}
 return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>{editing?'Editar tarea':'Nueva tarea'}</DialogTitle><DialogContent><Stack spacing={2} mt={1}>{error&&<Alert severity="error">{error}</Alert>}<TextField label="Tarea" value={f.title} onChange={e=>setF({...f,title:e.target.value})} autoFocus/><FormControl><InputLabel>Categoría</InputLabel><Select value={f.category_id} label="Categoría" onChange={e=>setF({...f,category_id:e.target.value})}>{categories.map(c=><MenuItem key={c.id} value={c.id}>{c.name}</MenuItem>)}</Select></FormControl><TextField label="Fecha límite" type="date" value={f.due_date} onChange={e=>setF({...f,due_date:e.target.value})} InputLabelProps={{shrink:true}}/><FormControl><InputLabel>Cliente (opcional)</InputLabel><Select value={f.client_id} label="Cliente (opcional)" onChange={e=>setF({...f,client_id:e.target.value})}><MenuItem value="">Sin cliente</MenuItem>{clients.map(c=><MenuItem key={c.id} value={c.id}>{c.full_name}</MenuItem>)}</Select></FormControl><TextField label="Notas" multiline minRows={2} value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/>{!editing&&<Alert severity="info">Por ahora la tarea queda asignada al usuario que la crea. La base ya admite varios responsables cuando agreguemos gestión de usuarios.</Alert>}</Stack></DialogContent><DialogActions><Button onClick={onClose}>Cancelar</Button><Button variant="contained" onClick={save}>Guardar</Button></DialogActions></Dialog>
}
